const BLOB='c455e92c8b548620ee8eea8ed1d067ebd485bbe3';
const API='https://api.github.com/repos/GGG250870/ORDINI_HD_Accademia/git/blobs/'+BLOB;
const S={p:[],f:[],cat:'ALL',q:'',v:0,page:40,cart:JSON.parse(localStorage.hd_cart_v3||'{}'),cur:null};
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(n||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const init=s=>String(s||'HD').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
function save(){localStorage.hd_cart_v3=JSON.stringify(S.cart)}
async function load(){bind();let cached=localStorage.hd_products_v3; if(cached){S.p=JSON.parse(cached);ready();return} try{let r=await fetch(API);let j=await r.json();let html=decode(j.content);let m=html.match(/var P=(\[.*?\]);\s*var /s);if(!m)throw Error('catalogo');S.p=JSON.parse(m[1]).map(x=>({id:String(x.id),t:x.nome,c:x.cat,d:(x.nome+' - '+x.cat+' | Prodotto professionale per unghie HDNails®'),p:x.prezzo,ps:x.prezzo_str,promo:x.promo||''}));localStorage.hd_products_v3=JSON.stringify(S.p);ready()}catch(e){$('#status').textContent='Errore caricamento catalogo. Apri la pagina con connessione internet la prima volta.'}}
function decode(b64){let bin=atob(b64.replace(/\s/g,'')),arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);return new TextDecoder('utf-8').decode(arr)}
function ready(){chips();filter();cartUI();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})}
function bind(){$('#search').oninput=e=>{S.q=e.target.value.toLowerCase().trim();S.cat='ALL';setChip();filter()};$('#clear').onclick=()=>{$('#search').value='';S.q='';filter()};$('#more').onclick=more;$('#cartBtn').onclick=openCart;$('#bottomOpen').onclick=openCart;$('#overlay').onclick=closeAll;$('#closeD').onclick=closeAll;$('#closeC').onclick=closeAll;$('#addD').onclick=()=>{if(S.cur!=null)qty(S.cur,1);closeAll()};$('#wa').onclick=wa;$('#mail').onclick=mail;$('#print').onclick=printOrder;$('#clearCart').onclick=()=>{S.cart={};save();cartUI();render();closeAll()}}
function chips(){let c={};S.p.forEach(x=>c[x.c]=(c[x.c]||0)+1);let h='<button class="chip on" data-c="ALL">Tutti '+S.p.length+'</button>';Object.keys(c).sort().forEach(k=>h+=`<button class="chip" data-c="${esc(k)}">${esc(k)} ${c[k]}</button>`);$('#chips').innerHTML=h;$$('.chip').forEach(b=>b.onclick=()=>{S.cat=b.dataset.c;S.q='';$('#search').value='';setChip();filter()})}
function setChip(){$$('.chip').forEach(b=>b.classList.toggle('on',b.dataset.c===S.cat))}
function filter(){S.f=S.p.filter(x=>(S.cat==='ALL'||x.c===S.cat)&&(!S.q||(x.t+' '+x.c+' '+x.d).toLowerCase().includes(S.q)));S.v=0;$('#grid').innerHTML='';$('#status').textContent=(S.cat==='ALL'?'Tutti i prodotti':S.cat)+' ('+S.f.length+')';more()}
function more(){let from=S.v;S.v=Math.min(S.v+S.page,S.f.length);let h='';for(let i=from;i<S.v;i++)h+=card(S.f[i]);$('#grid').insertAdjacentHTML('beforeend',h);$('#more').style.display=S.v<S.f.length?'block':'none';if(!S.f.length)$('#grid').innerHTML='<div class="empty">Nessun prodotto trovato</div>'}
function card(x){let q=S.cart[x.id]||0;return `<div class="card"><div class="thumb" onclick="detail('${x.id}')"><div class="mark">${esc(init(x.t))}</div></div>${x.promo?`<div class="promo">${esc(x.promo)}</div>`:''}<div class="body"><div class="name">${esc(x.t)}</div><div class="cat">${esc(x.c)}</div><div class="price">${esc(x.ps)}</div></div><div class="foot"><button class="minus" onclick="qty('${x.id}',-1)">-</button><b id="q${x.id}">${q}</b><button class="plus" onclick="qty('${x.id}',1)">+</button><button id="a${x.id}" class="add ${q?'added':''}" onclick="qty('${x.id}',1)">${q?'OK':'+ Carrello'}</button></div></div>`}
function prod(id){return S.p.find(x=>x.id==id)}
window.qty=function(id,d){let n=Math.max(0,(S.cart[id]||0)+d);if(n)S.cart[id]=n;else delete S.cart[id];save();let q=$('#q'+id),a=$('#a'+id);if(q)q.textContent=n;if(a){a.textContent=n?'OK':'+ Carrello';a.classList.toggle('added',!!n)}cartUI();if($('#cart').classList.contains('on'))renderCart()}
window.detail=function(id){let x=prod(id);if(!x)return;S.cur=id;$('#dImg').innerHTML=`<div class="mark">${esc(init(x.t))}</div>`;$('#dTitle').textContent=x.t;$('#dCat').textContent=x.c;$('#dPrice').textContent=x.ps;$('#dDesc').textContent=x.d;$('#overlay').classList.add('on');$('#detail').classList.add('on')}
function cartUI(){let q=0,t=0;Object.keys(S.cart).forEach(id=>{let x=prod(id);if(x){q+=S.cart[id];t+=S.cart[id]*x.p}});$('#cc').textContent=q;$('#bt').textContent=money(t);$('#bi').textContent=q+' articoli';$('#bottom').style.display=q?'flex':'none'}
function openCart(){renderCart();$('#overlay').classList.add('on');$('#cart').classList.add('on')}function closeAll(){$('#overlay').classList.remove('on');$('#detail').classList.remove('on');$('#cart').classList.remove('on')}
function renderCart(){let ids=Object.keys(S.cart).filter(id=>prod(id));if(!ids.length){$('#cartItems').innerHTML='<div class="empty">Carrello vuoto</div>';$('#totals').innerHTML='';return}let h='',sub=0,n=0;ids.forEach(id=>{let x=prod(id),q=S.cart[id],line=q*x.p;sub+=line;n+=q;h+=`<div class="row"><div class="mark">${esc(init(x.t))}</div><div class="info"><b>${esc(x.t)}</b><div class="small">${x.ps} x ${q} = ${money(line)}</div><button onclick="qty('${id}',-1)">-</button> <b>${q}</b> <button onclick="qty('${id}',1)">+</button></div><button onclick="removeIt('${id}')">x</button></div>`});$('#cartItems').innerHTML=h;$('#totals').innerHTML=`<div>Subtotale: <b>${money(sub)}</b></div><div>Bonus 10% in prodotto: <b>${money(sub*.10)}</b></div><div><b>Totale: ${money(sub)}</b></div>`}
window.removeIt=id=>{delete S.cart[id];save();cartUI();renderCart();render()}
function req(){if(!Object.keys(S.cart).length){alert('Aggiungi prodotti al carrello');return false}if(!$('#cust').value.trim()){alert('Inserisci ragione sociale o dati spedizione');$('#cust').focus();return false}return true}
function text(){let sub=0,msg='ORDINE HD NAILS - Accademia Savona\n\nCliente/spedizione:\n'+$('#cust').value.trim()+'\n\n';Object.keys(S.cart).forEach(id=>{let x=prod(id);if(x){let q=S.cart[id],line=q*x.p;sub+=line;msg+=q+' x '+x.t+' = '+money(line)+'\n'}});msg+='\nTotale: '+money(sub)+'\nBonus 10% in prodotto: +'+money(sub*.10);let note=$('#note').value.trim();if(note)msg+='\n\nNote: '+note;return msg}
function wa(){if(req())location.href='https://wa.me/?text='+encodeURIComponent(text())}function mail(){if(req())location.href='mailto:?subject='+encodeURIComponent('Ordine HD Nails')+'&body='+encodeURIComponent(text())}
function printOrder(){if(!req())return;$('#printArea').innerHTML='<h1>HD NAILS - Ordine</h1><pre>'+esc(text())+'</pre>';window.print()}
load();