const ORDER_EMAIL='ordiniaccademiadisavona@gmail.com';
const ORDER_WA='393924983127';
const CATEGORY_ORDER=['nuova collezione','prodotti in sconto','best seller','limited edition','kit hdnails in offerta','kit ricostruzione','gel da ricostruzione','gel in bottiglia','base gel semipermanente','base gel','smalti semipermanenti','gelac colors','acrygel','preparatori and liquidi','preparatori','liquidi','lucidi top gloss','dual form','tip','attrezzature','lime buffer','lime','trattamento mani','pedicure','pennelli','strumenti','acrilico','color gel','nail art e decorazioni','glitter','polvere cromata','altri prodotti'];
const S={p:[],f:[],cat:'ALL',q:'',v:0,page:40,cart:JSON.parse(localStorage.hd_cart_v6||'{}'),cur:null,mode:'ALL',fav:JSON.parse(localStorage.hd_fav_v1||'[]'),client:JSON.parse(localStorage.hd_client_v1||'{}')};
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(n||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const init=s=>String(s||'HD').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
function save(){localStorage.hd_cart_v6=JSON.stringify(S.cart)}
function saveFav(){localStorage.hd_fav_v1=JSON.stringify(S.fav)}
function normCat(c){c=String(c||'').trim();return c||'Altri prodotti'}
function rankCat(c){let n=normCat(c).toLowerCase(),best=999;CATEGORY_ORDER.forEach((k,i)=>{if(n.includes(k)&&i<best)best=i});return best}
function sortProducts(a,b){let ra=rankCat(a.categoria),rb=rankCat(b.categoria);if(ra!==rb)return ra-rb;let ca=normCat(a.categoria),cb=normCat(b.categoria);if(ca!==cb)return ca.localeCompare(cb,'it');return String(a.nome||'').localeCompare(String(b.nome||''),'it')}
async function load(){bind();loadProfile();try{let r=await fetch('prodotti.json?v=5',{cache:'no-store'});S.p=await r.json();S.p=S.p.map(x=>({...x,categoria:normCat(x.categoria)})).sort(sortProducts);localStorage.hd_products_v6=JSON.stringify(S.p);ready()}catch(e){let c=localStorage.hd_products_v6;if(c){S.p=JSON.parse(c);ready()}else $('#status').textContent='Catalogo non caricato: apri una volta con connessione internet.'}}
function ready(){chips();filter();cartUI();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})}
function bind(){
$('#search').oninput=e=>{S.q=e.target.value.toLowerCase().trim();S.cat='ALL';S.mode='ALL';setChip();filter()};
$('#clear').onclick=()=>{$('#search').value='';S.q='';S.mode='ALL';filter()};
$('#more').onclick=more;$('#cartBtn').onclick=openCart;$('#bottomOpen').onclick=openCart;$('#overlay').onclick=closeAll;$('#closeD').onclick=closeAll;$('#closeC').onclick=closeAll;
$('#addD').onclick=()=>{if(S.cur!=null)qty(S.cur,1);closeAll()};$('#wa').onclick=wa;$('#mail').onclick=mail;$('#print').onclick=printOrder;$('#clearCart').onclick=()=>{S.cart={};save();cartUI();renderCart();closeAll();filter()};
let p=$('#profileBtn');if(p)p.onclick=openProfile;let cp=$('#closeP');if(cp)cp.onclick=closeAll;let sp=$('#saveProfile');if(sp)sp.onclick=saveProfile;let clr=$('#clearProfile');if(clr)clr.onclick=clearProfile;
let no=$('#newOrder');if(no)no.onclick=()=>{S.mode='ALL';S.cat='ALL';S.q='';$('#search').value='';setChip();filter();document.querySelector('main').scrollIntoView({behavior:'smooth'})};
let rb=$('#reorder');if(rb)rb.onclick=reorderLast;let fb=$('#favBtn');if(fb)fb.onclick=()=>{S.mode='FAV';S.cat='ALL';setChip();filter();document.querySelector('main').scrollIntoView({behavior:'smooth'})};
let nb=$('#newsBtn');if(nb)nb.onclick=()=>{S.mode='NEWS';S.cat='ALL';setChip();filter();document.querySelector('main').scrollIntoView({behavior:'smooth'})};
let fd=$('#favDetail');if(fd)fd.onclick=toggleFavCurrent;
}
function chips(){let c={};S.p.forEach(x=>c[normCat(x.categoria)]=(c[normCat(x.categoria)]||0)+1);let cats=Object.keys(c).sort((a,b)=>{let ra=rankCat(a),rb=rankCat(b);return ra!==rb?ra-rb:a.localeCompare(b,'it')});let h='<button class="chip on" data-c="ALL">Tutti '+S.p.length+'</button>';cats.forEach(k=>h+=`<button class="chip" data-c="${esc(k)}">${esc(k)} ${c[k]}</button>`);$('#chips').innerHTML=h;$$('.chip').forEach(b=>b.onclick=()=>{S.mode='ALL';S.cat=b.dataset.c;S.q='';$('#search').value='';setChip();filter()})}
function setChip(){$$('.chip').forEach(b=>b.classList.toggle('on',b.dataset.c===S.cat&&S.mode==='ALL'))}
function filter(){let arr=S.p;if(S.mode==='FAV')arr=arr.filter(x=>S.fav.includes(x.id));if(S.mode==='NEWS')arr=arr.slice(-60).reverse();S.f=arr.filter(x=>(S.cat==='ALL'||normCat(x.categoria)===S.cat)&&(!S.q||(x.nome+' '+x.categoria+' '+x.descrizione+' '+x.sku).toLowerCase().includes(S.q))).sort(sortProducts);S.v=0;$('#grid').innerHTML='';let label=S.mode==='FAV'?'Preferiti':S.mode==='NEWS'?'Novità':(S.cat==='ALL'?'Tutti i prodotti':S.cat);$('#status').textContent=label+' ('+S.f.length+')';more()}
function more(){let from=S.v;S.v=Math.min(S.v+S.page,S.f.length);let h='';for(let i=from;i<S.v;i++)h+=card(S.f[i]);$('#grid').insertAdjacentHTML('beforeend',h);$('#more').style.display=S.v<S.f.length?'block':'none';if(!S.f.length)$('#grid').innerHTML='<div class="empty">Nessun prodotto trovato</div>'}
function imgTag(x,cls='prodImg'){return x.immagine?`<img class="${cls}" src="${esc(x.immagine)}" alt="${esc(x.nome)}" loading="lazy" onerror="this.replaceWith(fallbackMark('${esc(init(x.nome))}'))">`:`<div class="mark">${esc(init(x.nome))}</div>`}
window.fallbackMark=function(t){let d=document.createElement('div');d.className='mark';d.textContent=t;return d}
function card(x){let q=S.cart[x.id]||0;let star=S.fav.includes(x.id)?'⭐ ':'';return `<div class="card"><div class="thumb" onclick="detail('${x.id}')">${imgTag(x)}</div><div class="body"><div class="name">${star}${esc(x.nome)}</div><div class="cat">${esc(normCat(x.categoria))}</div><div class="price">${esc(x.prezzo_str)}</div></div><div class="foot"><button class="minus" onclick="qty('${x.id}',-1)">-</button><b id="q${x.id}">${q}</b><button class="plus" onclick="qty('${x.id}',1)">+</button><button id="a${x.id}" class="add ${q?'added':''}" onclick="qty('${x.id}',1)">${q?'OK':'+ Carrello'}</button></div></div>`}
function prod(id){return S.p.find(x=>x.id==id)}
window.qty=function(id,d){let n=Math.max(0,(S.cart[id]||0)+d);if(n)S.cart[id]=n;else delete S.cart[id];save();let q=$('#q'+id),a=$('#a'+id);if(q)q.textContent=n;if(a){a.textContent=n?'OK':'+ Carrello';a.classList.toggle('added',!!n)}cartUI();if($('#cart').classList.contains('on'))renderCart()}
window.detail=function(id){let x=prod(id);if(!x)return;S.cur=id;$('#dImg').innerHTML=imgTag(x,'detailImg');$('#dTitle').textContent=x.nome;$('#dCat').textContent=normCat(x.categoria);$('#dPrice').textContent=x.prezzo_str;$('#dAvail').textContent=x.disponibilita||'';$('#dDesc').textContent=x.descrizione||'Descrizione non disponibile';$('#dSpec').textContent=x.specifiche||'';$('#specWrap').style.display=x.specifiche?'block':'none';let f=$('#favDetail');if(f)f.textContent=S.fav.includes(id)?'⭐ Rimuovi dai preferiti':'⭐ Aggiungi ai preferiti';$('#overlay').classList.add('on');$('#detail').classList.add('on')}
function toggleFavCurrent(){if(S.cur==null)return;let i=S.fav.indexOf(S.cur);if(i>=0)S.fav.splice(i,1);else S.fav.push(S.cur);saveFav();detail(S.cur);filter()}
function cartUI(){let q=0,t=0;Object.keys(S.cart).forEach(id=>{let x=prod(id);if(x){q+=S.cart[id];t+=S.cart[id]*x.prezzo}});$('#cc').textContent=q;$('#bt').textContent=money(t);$('#bi').textContent=q+' articoli';$('#bottom').style.display=q?'flex':'none'}
function openCart(){fillCustFromClient();renderCart();$('#overlay').classList.add('on');$('#cart').classList.add('on')}function closeAll(){$('#overlay').classList.remove('on');['detail','cart','profile'].forEach(id=>{let e=$('#'+id);if(e)e.classList.remove('on')})}
function renderCart(){let ids=Object.keys(S.cart).filter(id=>prod(id));if(!ids.length){$('#cartItems').innerHTML='<div class="empty">Carrello vuoto</div>';$('#totals').innerHTML='';return}let h='',sub=0;ids.forEach(id=>{let x=prod(id),q=S.cart[id],line=q*x.prezzo;sub+=line;h+=`<div class="row"><div class="miniPic">${imgTag(x,'cartImg')}</div><div class="info"><b>${esc(x.nome)}</b><div class="small">${x.prezzo_str} x ${q} = ${money(line)}</div><button onclick="qty('${id}',-1)">-</button> <b>${q}</b> <button onclick="qty('${id}',1)">+</button></div><button onclick="removeIt('${id}')">x</button></div>`});$('#cartItems').innerHTML=h;$('#totals').innerHTML=`<div>Subtotale: <b>${money(sub)}</b></div><div>Bonus 10% in prodotto: <b>${money(sub*.10)}</b></div><div><b>Totale: ${money(sub)}</b></div>`}
window.removeIt=id=>{delete S.cart[id];save();cartUI();renderCart();filter()}
function req(){if(!Object.keys(S.cart).length){alert('Aggiungi prodotti al carrello');return false}if(!$('#cust').value.trim()){alert('Inserisci ragione sociale o dati spedizione');$('#cust').focus();return false}return true}
function clientText(){let c=S.client, parts=[c.nome,c.piva,c.indirizzo,[c.cap,c.citta,c.prov].filter(Boolean).join(' '),c.tel,c.email].filter(Boolean);return parts.join('\n')}
function text(){let sub=0,now=new Date().toLocaleString('it-IT'),cust=$('#cust').value.trim()||clientText();let msg='ORDINE ACCADEMIA DI SAVONA\nData: '+now+'\n\nCliente/spedizione:\n'+cust+'\n\n';Object.keys(S.cart).forEach(id=>{let x=prod(id);if(x){let q=S.cart[id],line=q*x.prezzo;sub+=line;msg+=q+' x '+x.nome+' = '+money(line)+'\n'}});msg+='\nTotale: '+money(sub)+'\nBonus 10% in prodotto: +'+money(sub*.10);let note=$('#note').value.trim();if(note)msg+='\n\nNote: '+note;return msg}
function saveOrder(){let hist=JSON.parse(localStorage.hd_orders_v1||'[]');hist.unshift({date:new Date().toISOString(),cart:S.cart,client:S.client});localStorage.hd_orders_v1=JSON.stringify(hist.slice(0,20));localStorage.hd_last_cart_v1=JSON.stringify(S.cart)}
function csvCell(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}
function downloadDaneaCsv(){let ids=Object.keys(S.cart).filter(id=>prod(id));if(!ids.length)return;let now=new Date();let ordine='ORD-'+now.getFullYear()+String(now.getMonth()+1).padStart(2,'0')+String(now.getDate()).padStart(2,'0')+'-'+String(now.getHours()).padStart(2,'0')+String(now.getMinutes()).padStart(2,'0')+String(now.getSeconds()).padStart(2,'0');let c=S.client||{};let rows=[['NumeroOrdine','Data','Cliente','PartitaIVA_CF','Indirizzo','CAP','Citta','Provincia','Telefono','Email','CodiceArticolo','Descrizione','Quantita','PrezzoUnitario','TotaleRiga','Note']];ids.forEach(id=>{let x=prod(id),q=S.cart[id],line=q*x.prezzo;rows.push([ordine,now.toLocaleDateString('it-IT'),c.nome||$('#cust').value.trim(),c.piva||'',c.indirizzo||'',c.cap||'',c.citta||'',c.prov||'',c.tel||'',c.email||'',x.sku||x.id,x.nome,q,String(x.prezzo).replace('.',','),String(line.toFixed(2)).replace('.',','),$('#note').value.trim()])});let csv='\ufeff'+rows.map(r=>r.map(csvCell).join(';')).join('\r\n');let blob=new Blob([csv],{type:'text/csv;charset=utf-8'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=ordine+'_Danea_Easyfatt.csv';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
function wa(){if(req()){saveOrder();downloadDaneaCsv();location.href='https://wa.me/'+ORDER_WA+'?text='+encodeURIComponent(text())}}
function mail(){if(req()){saveOrder();downloadDaneaCsv();let subj='Ordine ORDINI_HD_ACCADEMIA - '+(S.client.nome||$('#cust').value.trim()||'Cliente');location.href='mailto:'+ORDER_EMAIL+'?subject='+encodeURIComponent(subj)+'&body='+encodeURIComponent(text())}}
function printOrder(){if(!req())return;saveOrder();downloadDaneaCsv();$('#printArea').innerHTML='<h1>ORDINI_HD_ACCADEMIA</h1><pre>'+esc(text())+'</pre>';window.print()}
function loadProfile(){let c=S.client;if($('#cl_nome')){['nome','piva','indirizzo','cap','citta','prov','tel','email'].forEach(k=>{let e=$('#cl_'+k);if(e)e.value=c[k]||''})}if(c.nome){$('#hello').textContent='Ciao '+c.nome;$('#welcome').textContent='Ciao '+c.nome+', benvenuta nell\'Accademia di Savona'}}
function saveProfile(){['nome','piva','indirizzo','cap','citta','prov','tel','email'].forEach(k=>{let e=$('#cl_'+k);S.client[k]=e?e.value.trim():''});localStorage.hd_client_v1=JSON.stringify(S.client);loadProfile();fillCustFromClient();closeAll();alert('Dati cliente salvati')}
function clearProfile(){S.client={};localStorage.removeItem('hd_client_v1');loadProfile();closeAll()}
function fillCustFromClient(){let t=clientText();if(t&&!$('#cust').value.trim())$('#cust').value=t}
function openProfile(){loadProfile();$('#overlay').classList.add('on');$('#profile').classList.add('on')}
function reorderLast(){let last=JSON.parse(localStorage.hd_last_cart_v1||'{}');if(!Object.keys(last).length){alert('Nessun ordine precedente trovato su questo dispositivo');return}S.cart=last;save();cartUI();filter();openCart()}
load();