const CATALOG_PATCH_VERSION='18';
function cpCsvRows(txt){let rows=[],row=[],cell='',q=false;for(let i=0;i<txt.length;i++){let ch=txt[i],nx=txt[i+1];if(ch==='"'&&q&&nx==='"'){cell+='"';i++;continue}if(ch==='"'){q=!q;continue}if(ch===','&&!q){row.push(cell);cell='';continue}if((ch==='\n'||ch==='\r')&&!q){if(ch==='\r'&&nx==='\n')i++;row.push(cell);if(row.some(v=>v!==''))rows.push(row);row=[];cell='';continue}cell+=ch}row.push(cell);if(row.some(v=>v!==''))rows.push(row);return rows}
function cpCsvObjects(txt){let rows=cpCsvRows(txt),head=rows.shift()||[];return rows.map(r=>Object.fromEntries(head.map((h,i)=>[h,r[i]||''])))}
function cpPriceNum(s){let m=String(s||'').replace(',','.').match(/[-+]?\d*\.?\d+/);return m?Number(m[0]):0}
function cpPriceLabel(n){return new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(n||0)}
function cpCat(title,desc){let t=((title||'')+' '+(desc||'')).toLowerCase();if(t.includes('kit'))return'Kit';if(/builder|costrutt|ricostruzione|monofas|monofase|cover/.test(t))return'Gel da Ricostruzione';if(/base gel|rubber base|fiber base|\bbase\b/.test(t))return'Base Gel';if(/semipermanent|gelac|smalto|color gel|colore|colors/.test(t))return'Smalti Semipermanenti';if(/acrygel|polygel|poly gel/.test(t))return'Acrygel';if(/top|gloss|lucid|sigillant/.test(t))return'Lucidi Top Gloss';if(/primer|cleaner|remover|prep|liquid|liquido/.test(t))return'Preparatori & Liquidi';if(/glitter|nail art|decor|strass|foil|pigment|cromo/.test(t))return'Nail Art & Decorazioni';if(/dual form|\btip\b|cartin/.test(t))return'Dual Form & Tip';if(/lima|lime|buffer/.test(t))return'Lime & Buffer';if(/pennell/.test(t))return'Pennelli';if(/lampada|fresa|attrezz/.test(t))return'Attrezzature';if(/pedicure|mani|mano|piede|cuticol/.test(t))return'Trattamento Mani';return'Altri prodotti'}
function cpMapProduct(r,i){let nome=(r.title||'').trim(),descr=(r.description||nome).trim(),prezzo=cpPriceNum(r.price),id=(r.id||('HDN-'+String(i+1).padStart(4,'0'))).trim();return{id,sku:id,nome,categoria:cpCat(nome,descr),descrizione:descr,specifiche:'',disponibilita:(r.availability||'').trim(),prezzo,prezzo_str:cpPriceLabel(prezzo),immagine:(r.image_link||'').trim(),link:(r.link||'').trim(),brand:(r.brand||'HDNails').trim()}}
function cpExtraProducts(){return[{id:'HDN-0966',sku:'HDN-0966',nome:'HEXA Lampada Unghie',categoria:'Attrezzature',descrizione:'HEXA Smart Lamp: lampada UV/LED professionale 71+7 LED con sensore a infrarossi, 4 timer e modalità low heat. Polimerizzazione perfetta anche sui pollici.',specifiche:'80 W, 71 + 7 LED dedicati al pollice, 4 timer, modalità low heat',disponibilita:'in stock',prezzo:79,prezzo_str:cpPriceLabel(79),immagine:'https://www.hdnails.it/media/catalog/product/cache/37a89782ee5d75b828ffe183f5318d59/h/e/hexa1.png',link:'https://www.hdnails.it/hexa-lampada-uv-led-unghie',brand:'HDNails'}]}
function cpMergeExtras(prodotti){let ids=new Set(prodotti.map(x=>String(x.id).toLowerCase())),names=new Set(prodotti.map(x=>String(x.nome).toLowerCase()));cpExtraProducts().forEach(x=>{if(!ids.has(x.id.toLowerCase())&&!names.has(x.nome.toLowerCase()))prodotti.push(x)});return prodotti}
async function cpLoadCatalogFromCsv(){try{let r=await fetch('HDNails_Catalogo_Facebook_Commerce.csv?v='+CATALOG_PATCH_VERSION,{cache:'no-store'});let txt=await r.text();let prodotti=cpMergeExtras(cpCsvObjects(txt).map(cpMapProduct).filter(x=>x.nome));if(!prodotti.length)throw Error('catalogo vuoto');S.p=prodotti.map(x=>({...x,categoria:typeof normCat==='function'?normCat(x.categoria):x.categoria})).sort(typeof sortProducts==='function'?sortProducts:(a,b)=>String(a.nome).localeCompare(String(b.nome),'it'));localStorage.hd_products_v8=JSON.stringify(S.p);if(typeof chips==='function')chips();if(typeof filter==='function')filter();if(typeof cartUI==='function')cartUI();let st=document.querySelector('#status');if(st&&S.p.length)st.textContent='Tutti i prodotti ('+S.p.length+')'}catch(e){console.warn('Catalogo CSV non caricato',e)}}
setTimeout(cpLoadCatalogFromCsv,500);